# Version: 0.0.1
FROM ubuntu:18.04
LABEL maintainer="shivamjha@example.com"
RUN apt-get update; apt-get install -y nginx
RUN echo 'Hi, This is Shivam Jha, running my first container'\
>/var/www/html/index.html
EXPOSE 80
